export enum IconsType {
  ICON_MINUS = 'ICON_MINUS',
  ICON_PLUS = 'ICON_PLUS',
  ICON_CLOSE = 'ICON_CLOSE',
  ICON_CART = 'ICON_CART',
  ICON_NO_CART = 'ICON_NO_CART',
  ICON_SEARCH = 'ICON_SEARCH',
  ICON_STAR = 'ICON_STAR',
  ICON_SAD_WARNING = 'ICON_SAD_WARNING',
  ICON_HAPPY_WARNING = 'ICON_HAPPY_WARNING',
}
