export enum ContainerType {
  // BANNER
  BANNER_SINGLE = 'BANNER_SINGLE',
  // CATALOG
  CATALOG_SPOTLIGHT = 'CATALOG_SPOTLIGHT',
  CATALOG_SEARCH = 'CATALOG_SEARCH',
  CATALOG_SUGGESTION = 'CATALOG_SUGGESTION',
  // CART
  CART_BUTTON = 'CART_BUTTON',
  CART_QUANTITY_CONTROL = 'CART_QUANTITY_CONTROL',
}
